const test = require("node:test");
const assert = require("node:assert");

const {
  buildTimeZoneCountries,
  renderTimeZoneCountries,
} = require("../generate-time-zone-countries.mjs");

const lookup = (zonesByCountry) => (country) => zonesByCountry[country];

test("maps a zone claimed by one country to that country", () => {
  const table = buildTimeZoneCountries({
    countries: ["JP"],
    timeZonesOf: lookup({ JP: ["Asia/Tokyo"] }),
    overrides: {},
  });

  assert.deepStrictEqual(table, { "Asia/Tokyo": { country: "JP" } });
});

test("keeps the first country for a shared zone when all claimants share an outcome", () => {
  const table = buildTimeZoneCountries({
    countries: ["DE", "FR"],
    timeZonesOf: lookup({
      DE: ["Europe/Berlin", "Europe/Shared"],
      FR: ["Europe/Paris", "Europe/Shared"],
    }),
    overrides: {},
  });

  assert.deepStrictEqual(table, {
    "Europe/Berlin": { country: "DE" },
    "Europe/Paris": { country: "FR" },
    "Europe/Shared": { country: "DE" },
  });
});

test("drops a shared zone whose claimants have different outcomes", () => {
  const table = buildTimeZoneCountries({
    countries: ["US", "CA"],
    timeZonesOf: lookup({
      US: ["America/New_York", "America/Shared"],
      CA: ["America/Vancouver", "America/Shared"],
    }),
    overrides: {},
  });

  assert.deepStrictEqual(table, {
    "America/New_York": { country: "US" },
    "America/Vancouver": { country: "CA" },
  });
});

test("treats Switzerland as part of the European opt-in outcome", () => {
  const table = buildTimeZoneCountries({
    countries: ["CH", "GB"],
    timeZonesOf: lookup({
      CH: ["Europe/Zurich", "Europe/Shared"],
      GB: ["Europe/London", "Europe/Shared"],
    }),
    overrides: {},
  });

  assert.deepStrictEqual(table["Europe/Shared"], { country: "CH" });
  assert.deepStrictEqual(table["Europe/Zurich"], { country: "CH" });
});

test("drops a zone shared between Switzerland and the rest of the world", () => {
  const table = buildTimeZoneCountries({
    countries: ["CH", "JP"],
    timeZonesOf: lookup({
      CH: ["Europe/Shared"],
      JP: ["Europe/Shared"],
    }),
    overrides: {},
  });

  assert.deepStrictEqual(table, {});
});

test("adds the region overrides even when the lookup does not return their zones", () => {
  const table = buildTimeZoneCountries({
    countries: ["CA", "US"],
    timeZonesOf: lookup({ CA: ["America/Vancouver"], US: ["America/Denver"] }),
  });

  assert.deepStrictEqual(table["America/Montreal"], { country: "CA", region: "QC" });
  assert.deepStrictEqual(table["America/Toronto"], { country: "CA", region: "QC" });
  assert.deepStrictEqual(table["America/Los_Angeles"], { country: "US", region: "CA" });
  assert.deepStrictEqual(table["America/Vancouver"], { country: "CA" });
});

test("replaces a claimed zone with its region override", () => {
  const table = buildTimeZoneCountries({
    countries: ["US"],
    timeZonesOf: lookup({ US: ["America/Los_Angeles"] }),
    overrides: { "America/Los_Angeles": { country: "US", region: "CA" } },
  });

  assert.deepStrictEqual(table, { "America/Los_Angeles": { country: "US", region: "CA" } });
});

test("ignores countries whose lookup returns nothing", () => {
  const table = buildTimeZoneCountries({
    countries: ["BV"],
    timeZonesOf: () => undefined,
    overrides: {},
  });

  assert.deepStrictEqual(table, {});
});

test("renders a generated header and one entry per zone", () => {
  const source = renderTimeZoneCountries({
    "America/Toronto": { country: "CA", region: "QC" },
    "Asia/Tokyo": { country: "JP" },
  });

  assert.strictEqual(
    source,
    [
      "// Generated by scripts/generate-time-zone-countries.mjs. Do not edit.",
      "export const timeZoneCountries: Record<string, { country: string; region?: string }> = {",
      '  "America/Toronto": { country: "CA", region: "QC" },',
      '  "Asia/Tokyo": { country: "JP" },',
      "};",
      "",
    ].join("\n")
  );
});
